# fly.toml app configuration file generated for eduhub on 2023-12-30T21:52:51+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "eduhub"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
