spring.data.mongodb.uri=mongodb://localhost:27017/educluster?directConnection=true
spring.data.mongodb.database=educluster
server.port=8080
java.runtime.version=17
spring.web.resources.add-mappings=true
server.error.include-message=always
spring.web.resources.static-locations=classpath:/static/
springdoc.swagger-ui.path=/swagger-ui.html
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
firebase.bucket-name=apartify-2fd8c.appspot.com
firebase.app-name=apartify-2fd8c
firebase.class-path=eduhub-key.json
firebase.key-name=eduhub-key.json
firebase.download-url=https://firebasestorage.googleapis.com/v0/b/edu-hub-3772f.appspot.com/o/%s?alt=media
firebase.database-url=https://apartify-2fd8c-default-rtdb.asia-southeast1.firebasedatabase.app
